server:
  port: 8083

spring:
  application:
    name: gateway-service

#  cloud:
#    gateway:
#      httpclient:
#        connect-timeout: 5000
#        response-timeout: 5s
#
#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users/**
#          filters:
#            - StripPrefix=1
#
#        - id: auth-service
#          uri: lb://AUTH-SERVICE
#          predicates:
#            - Path=/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-User-Id, #{authentication.name}
        - AddRequestHeader=X-Roles, #{authentication.authorities}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

