server:
  port: 8083

spring:
  application:
    name: gateway-service
  redis:
    host: 192.168.1.7
    port: 6379
    timeout: 2s
    lettuce:
      pool:
        max-active: 50
        max-idle: 20
        min-idle: 5
        max-wait: 10s

#  cloud:
#    gateway:
#      default-filters:
#        - name: CircuitBreaker
#          args:
#            name: globalCircuitBreaker
#            fallbackUri: forward:/fallback/global

#  cloud:
#    gateway:
#      httpclient:
#        connect-timeout: 5000
#        response-timeout: 5s
#
#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/users/**
#          filters:
#            - StripPrefix=1
#
#        - id: auth-service
#          uri: lb://AUTH-SERVICE
#          predicates:
#            - Path=/auth/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/.well-known/jwks.json

  cloud:
    gateway:
      redis-rate-limiter:
        enabled: true
      default-filters:
        - AddRequestHeader=X-User-Id, #{authentication.name}
        - AddRequestHeader=X-Roles, #{authentication.authorities}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.filter.ratelimit: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      authCB:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      userCreateCB:
        slidingWindowSize: 10
        failureRateThreshold: 40
        waitDurationInOpenState: 15s

      userProtectedCB:
        slidingWindowSize: 20
        failureRateThreshold: 30
        waitDurationInOpenState: 20s
